pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
        jdk 'JDK17'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/BrajdeepSingh8172/Projects.git',
                    credentialsId: 'your-github-credential-id'
            }
        }

        stage('Build WAR') {
            steps {
                sh "mvn -f wordcount-webapplication/java-maven-webapp/pom.xml clean package"
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t wordcount-app ./wordcount-webapplication"
            }
        }

        stage('Run Docker Container') {
            steps {
                sh "docker run -d -p 8081:8080 --name wordcount-container wordcount-app || true"
            }
        }
    }
}
