pipeline {
    agent any

    tools {
        maven 'Maven-3.9'
        jdk 'JDK17'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/BrajdeepSingh8172/Projects.git',
                    credentialsId: 'github-token'   // ← your actual credential ID
            }
        }

        stage('Build WAR') {
            steps {
                bat "mvn -f wordcount-webapplication/java-maven-webapp/pom.xml clean package"
            }
        }

        stage('Build Docker Image') {
            steps {
                bat "docker build -t wordcount-app ./wordcount-webapplication"
            }
        }

        stage('Run Docker Container') {
            steps {

                // Stop & remove old container safely
                bat "docker rm -f wordcount-container || exit 0"

                // Run new container on port 8081
                bat "docker run -d -p 8081:8080 --name wordcount-container wordcount-app"
            }
        }
    }
}
